name: Verify Service Account Secret

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Check secret format
        run: |
          # Write the secret to a temporary file
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}" > temp_key.json
          
          # Check if it's valid JSON
          if jq empty temp_key.json 2>/dev/null; then
            echo "✅ Secret is valid JSON"
            
            # Check if it has the expected fields
            if jq -e '.type == "service_account"' temp_key.json > /dev/null && \
               jq -e '.project_id' temp_key.json > /dev/null && \
               jq -e '.private_key' temp_key.json > /dev/null && \
               jq -e '.client_email' temp_key.json > /dev/null; then
              echo "✅ Secret contains expected service account fields"
              echo "✅ Project ID: $(jq -r '.project_id' temp_key.json)"
              echo "✅ Client email: $(jq -r '.client_email' temp_key.json)"
            else
              echo "❌ Secret is missing expected service account fields"
            fi
          else
            echo "❌ Secret is not valid JSON"
            # Print first few characters to see if it's completely wrong
            echo "First 20 characters of secret: $(echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}" | cut -c 1-20)..."
          fi
          
          # Clean up
          rm temp_key.json
